version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/crudjwt
      
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
